language: python
python:
  - "2.7"
  - "3.6"
before_install:
  - pip install --upgrade pytest
install:
    - pip install -r requirements.txt
    - pip install coveralls
script:
    - coverage run --source='.' -m pytest --pylint --flake8
after_success:
    - coveralls
